/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author BEELZEBUB
 */
package tiket.bioskop;

import java.awt.HeadlessException;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class Menu5 extends javax.swing.JFrame {

    /**
     * Creates new form Menu5
     */
    public Menu5() {
        initComponents();
        tampil_data();
        id_film_otomatis();
    }
    
    public void bersih(){
        txtIDFilm.setText(null);
        txtJudulFilm.setText(null);
        txtDurasiFilm.setText(null);
        txtRatingUsia.setText(null);
        txtStudio.setText(null);
    }
    public void id_film_otomatis() {
    try {
        // Mendapatkan koneksi dari kelas Koneksi
            Connection connection = tiket.bioskop.Koneksi.getKoneksi();
            String query = "SELECT * FROM tbl_film ORDER BY id_film DESC";
            PreparedStatement statement = connection.prepareStatement(query);
            ResultSet resultSet = statement.executeQuery();
            if (resultSet.next()) {
                String id = resultSet.getString(1);
                int nextId = Integer.parseInt(id.substring(1)) + 1;
                String AN = String.format("%03d", nextId);
                txtIDFilm.setText("F" + AN);
            } else {
                txtIDFilm.setText("F001");
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
    
    public void tampil_data(){
        DefaultTableModel tabel = new DefaultTableModel();
        tabel.addColumn("ID Film");
        tabel.addColumn("Judul Film");
        tabel.addColumn("Durasi Film");
        tabel.addColumn("Rating Usia");
        tabel.addColumn("Studio");
        try{
            java.sql.Connection conn=(java.sql.Connection)tiket.bioskop.Koneksi.getKoneksi();
            String sql = "SELECT * FROM tbl_film ";
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            ResultSet rs=pst.executeQuery(sql);
            while(rs.next())
            {
                tabel.addRow(new Object[]{
                rs.getString(1),
                rs.getString(2),
                rs.getString(3),
                rs.getString(4),
                rs.getString(5)});
        }jTable1.setModel(tabel);
        }catch (Exception e){
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtStudio = new javax.swing.JTextField();
        btnHapus = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnSimpan = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        buttonKembali = new javax.swing.JButton();
        txtRatingUsia = new javax.swing.JTextField();
        txtDurasiFilm = new javax.swing.JTextField();
        txtJudulFilm = new javax.swing.JTextField();
        txtIDFilm = new javax.swing.JTextField();
        Studio = new javax.swing.JLabel();
        RatingUsia = new javax.swing.JLabel();
        DurasiFilm = new javax.swing.JLabel();
        IdFilm = new javax.swing.JLabel();
        JudulFilm = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        txtStudio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStudioActionPerformed(evt);
            }
        });
        getContentPane().add(txtStudio);
        txtStudio.setBounds(640, 230, 100, 30);

        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });
        getContentPane().add(btnHapus);
        btnHapus.setBounds(590, 330, 80, 25);

        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        getContentPane().add(btnEdit);
        btnEdit.setBounds(490, 330, 80, 25);

        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });
        getContentPane().add(btnSimpan);
        btnSimpan.setBounds(390, 330, 80, 25);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID Film", "Judul Film", "Durasi Film", "Rating Usia", "Studio"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(310, 390, 460, 130);

        buttonKembali.setText("Kembali");
        buttonKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonKembaliActionPerformed(evt);
            }
        });
        getContentPane().add(buttonKembali);
        buttonKembali.setBounds(20, 10, 75, 25);

        txtRatingUsia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRatingUsiaActionPerformed(evt);
            }
        });
        getContentPane().add(txtRatingUsia);
        txtRatingUsia.setBounds(640, 190, 100, 30);

        txtDurasiFilm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDurasiFilmActionPerformed(evt);
            }
        });
        getContentPane().add(txtDurasiFilm);
        txtDurasiFilm.setBounds(390, 270, 100, 30);

        txtJudulFilm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJudulFilmActionPerformed(evt);
            }
        });
        getContentPane().add(txtJudulFilm);
        txtJudulFilm.setBounds(390, 230, 100, 30);

        txtIDFilm.setEnabled(false);
        txtIDFilm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDFilmActionPerformed(evt);
            }
        });
        getContentPane().add(txtIDFilm);
        txtIDFilm.setBounds(390, 190, 100, 30);

        Studio.setFont(new java.awt.Font("Microsoft Tai Le", 1, 14)); // NOI18N
        Studio.setForeground(new java.awt.Color(255, 255, 255));
        Studio.setText("Studio         :");
        getContentPane().add(Studio);
        Studio.setBounds(540, 230, 100, 30);

        RatingUsia.setFont(new java.awt.Font("Microsoft Tai Le", 1, 14)); // NOI18N
        RatingUsia.setForeground(new java.awt.Color(255, 255, 255));
        RatingUsia.setText("Rating Usia :");
        getContentPane().add(RatingUsia);
        RatingUsia.setBounds(540, 190, 90, 30);

        DurasiFilm.setFont(new java.awt.Font("Microsoft Tai Le", 1, 14)); // NOI18N
        DurasiFilm.setForeground(new java.awt.Color(255, 255, 255));
        DurasiFilm.setText("Durasi Film :");
        getContentPane().add(DurasiFilm);
        DurasiFilm.setBounds(300, 270, 120, 30);

        IdFilm.setFont(new java.awt.Font("Microsoft Tai Le", 1, 14)); // NOI18N
        IdFilm.setForeground(new java.awt.Color(255, 255, 255));
        IdFilm.setText("ID Film       :");
        getContentPane().add(IdFilm);
        IdFilm.setBounds(300, 190, 90, 30);

        JudulFilm.setFont(new java.awt.Font("Microsoft Tai Le", 1, 14)); // NOI18N
        JudulFilm.setForeground(new java.awt.Color(255, 255, 255));
        JudulFilm.setText("Judul Film  :");
        getContentPane().add(JudulFilm);
        JudulFilm.setBounds(300, 230, 100, 30);

        jLabel2.setFont(new java.awt.Font("Microsoft Tai Le", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Staff Mode : Film");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(450, 120, 210, 32);

        jPanel1.setBackground(new java.awt.Color(0, 0, 204));
        getContentPane().add(jPanel1);
        jPanel1.setBounds(230, 70, 610, 470);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Aset/bgfix.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, -10, 1080, 620);

        setBounds(0, 0, 1086, 639);
    }// </editor-fold>//GEN-END:initComponents

    private void txtIDFilmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDFilmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDFilmActionPerformed

    private void txtJudulFilmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJudulFilmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJudulFilmActionPerformed

    private void txtDurasiFilmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDurasiFilmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDurasiFilmActionPerformed

    private void txtRatingUsiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRatingUsiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRatingUsiaActionPerformed

    private void buttonKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonKembaliActionPerformed
        // TODO add your handling code here:
        Menu4A su=new Menu4A();
        su.show();
        dispose();
        
    }//GEN-LAST:event_buttonKembaliActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
        try {
    String idFilm = txtIDFilm.getText();
    String judulFilm = txtJudulFilm.getText();
    String durasiFilm = txtDurasiFilm.getText();
    String ratingUsia = txtRatingUsia.getText();
    String studio = txtStudio.getText();

    // Periksa kekosongan JTextField
    if (idFilm.isEmpty() || judulFilm.isEmpty() || durasiFilm.isEmpty() || ratingUsia.isEmpty() || studio.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Harap lengkapi semua field");
        return;
    }

    String sql = "INSERT INTO tbl_film VALUES(?, ?, ?, ?, ?)";
    java.sql.Connection conn = (java.sql.Connection) tiket.bioskop.Koneksi.getKoneksi();
    java.sql.PreparedStatement pst = conn.prepareStatement(sql);
    pst.setString(1, idFilm);
    pst.setString(2, judulFilm);
    pst.setString(3, durasiFilm);
    pst.setString(4, ratingUsia);
    pst.setString(5, studio);

    pst.execute();
    JOptionPane.showMessageDialog(null, "Berhasil disimpan");
    tampil_data();
    bersih();
    id_film_otomatis();
} catch (HeadlessException | SQLException e) {
    JOptionPane.showMessageDialog(null, "Gagal disimpan");
    System.out.println(e.getMessage());
}

    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        try {
    java.sql.Connection conn = (java.sql.Connection) tiket.bioskop.Koneksi.getKoneksi();
    String idFilm = txtIDFilm.getText();
    
    if (idFilm.isEmpty()) {
        JOptionPane.showMessageDialog(null, "ID Film tidak boleh kosong");
    } else {
        String sql = "DELETE FROM tbl_film WHERE id_film = ?";
        java.sql.PreparedStatement pst = conn.prepareStatement(sql);
        pst.setString(1, idFilm);
        int result = pst.executeUpdate();
        
        if (result > 0) {
            JOptionPane.showMessageDialog(null, "Data berhasil dihapus");
            tampil_data();
            bersih();
            id_film_otomatis();
        } else {
            JOptionPane.showMessageDialog(null, "Gagal menghapus data");
        }
    }
} catch (Exception e) {
    JOptionPane.showMessageDialog(null, "Proses Penghapusan Gagal");
    System.out.println(e.getMessage());
}

    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        try {
    String idFilm = txtIDFilm.getText();
    String judulFilm = txtJudulFilm.getText();
    String durasiFilm = txtDurasiFilm.getText();
    String ratingUsia = txtRatingUsia.getText();
    String studio = txtStudio.getText();
    
    if (idFilm.isEmpty() || judulFilm.isEmpty() || durasiFilm.isEmpty() || ratingUsia.isEmpty() || studio.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Harap lengkapi semua field");
    } else {
        String sql = "UPDATE tbl_film SET judul_film=?, durasi_film=?, rating_usia=?, studio=? WHERE id_film=?";
        java.sql.Connection conn = (java.sql.Connection) tiket.bioskop.Koneksi.getKoneksi();
        java.sql.PreparedStatement pst = conn.prepareStatement(sql);
        pst.setString(1, judulFilm);
        pst.setString(2, durasiFilm);
        pst.setString(3, ratingUsia);
        pst.setString(4, studio);
        pst.setString(5, idFilm);
        
        int result = pst.executeUpdate();
        
        if (result > 0) {
            JOptionPane.showMessageDialog(null, "Data berhasil disimpan");
            tampil_data();
            bersih();
            id_film_otomatis();
        } else {
            JOptionPane.showMessageDialog(null, "Gagal disimpan");
        }
    }
} catch (HeadlessException | SQLException e) {
    JOptionPane.showMessageDialog(null, "Gagal disimpan");
    System.out.println(e.getMessage());
}

    }//GEN-LAST:event_btnEditActionPerformed

    private void txtStudioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStudioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStudioActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
int selectedRow = jTable1.getSelectedRow();
if (selectedRow != -1) {
    String idFilm = jTable1.getValueAt(selectedRow, 0).toString();
    String judulFilm = jTable1.getValueAt(selectedRow, 1).toString();
    String durasiFilm = jTable1.getValueAt(selectedRow, 2).toString();
    String ratingUsia = jTable1.getValueAt(selectedRow, 3).toString();
    String studio = jTable1.getValueAt(selectedRow, 4).toString();

    txtIDFilm.setText(idFilm);
    txtJudulFilm.setText(judulFilm);
    txtDurasiFilm.setText(durasiFilm);
    txtRatingUsia.setText(ratingUsia);
    txtStudio.setText(studio);
}

        
    }//GEN-LAST:event_jTable1MouseClicked

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu5().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DurasiFilm;
    private javax.swing.JLabel IdFilm;
    private javax.swing.JLabel JudulFilm;
    private javax.swing.JLabel RatingUsia;
    private javax.swing.JLabel Studio;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton buttonKembali;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtDurasiFilm;
    private javax.swing.JTextField txtIDFilm;
    private javax.swing.JTextField txtJudulFilm;
    private javax.swing.JTextField txtRatingUsia;
    private javax.swing.JTextField txtStudio;
    // End of variables declaration//GEN-END:variables
}
