/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author BEELZEBUB
 */
package tiket.bioskop;

import java.awt.HeadlessException;
import java.sql.*;
import javax.swing.JOptionPane;
import tiket.bioskop.Menu4;

public class Menu4 extends javax.swing.JFrame {

    /**
     * Creates new form Menu4
     */
    String User;
    public Menu4() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Password = new javax.swing.JLabel();
        Username = new javax.swing.JLabel();
        LabelUsername = new javax.swing.JTextField();
        buttonLogin = new javax.swing.JButton();
        buttonKembali = new javax.swing.JButton();
        LabelPassword = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        LoginStaff = new javax.swing.JLabel();
        pww = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 0, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(null);

        Password.setFont(new java.awt.Font("Microsoft Tai Le", 1, 18)); // NOI18N
        Password.setForeground(new java.awt.Color(255, 255, 255));
        Password.setText("Password");
        jPanel1.add(Password);
        Password.setBounds(20, 90, 90, 24);

        Username.setFont(new java.awt.Font("Microsoft Tai Le", 1, 18)); // NOI18N
        Username.setForeground(new java.awt.Color(255, 255, 255));
        Username.setText("Username");
        jPanel1.add(Username);
        Username.setBounds(20, 50, 100, 24);

        LabelUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LabelUsernameActionPerformed(evt);
            }
        });
        jPanel1.add(LabelUsername);
        LabelUsername.setBounds(140, 50, 120, 22);

        buttonLogin.setText("Login");
        buttonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLoginActionPerformed(evt);
            }
        });
        jPanel1.add(buttonLogin);
        buttonLogin.setBounds(180, 140, 77, 25);

        buttonKembali.setText("Kembali");
        buttonKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonKembaliActionPerformed(evt);
            }
        });
        jPanel1.add(buttonKembali);
        buttonKembali.setBounds(50, 140, 75, 25);
        jPanel1.add(LabelPassword);
        LabelPassword.setBounds(140, 90, 120, 22);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(400, 320, 290, 190);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("CINEMA 256");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(430, 190, 220, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Aset/logofix1.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(410, 20, 250, 180);

        LoginStaff.setFont(new java.awt.Font("Microsoft Tai Le", 1, 18)); // NOI18N
        LoginStaff.setForeground(new java.awt.Color(255, 255, 255));
        LoginStaff.setText("Login Staff");
        getContentPane().add(LoginStaff);
        LoginStaff.setBounds(500, 290, 100, 20);

        pww.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Aset/bgfix.png"))); // NOI18N
        getContentPane().add(pww);
        pww.setBounds(0, 0, 1070, 600);

        setBounds(0, 0, 1086, 639);
    }// </editor-fold>//GEN-END:initComponents

    private void LabelUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LabelUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LabelUsernameActionPerformed

    private void buttonKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonKembaliActionPerformed
        // TODO add your handling code here:
        Menu1 su=new Menu1();
        su.show();
        dispose();
    }//GEN-LAST:event_buttonKembaliActionPerformed

    private void buttonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLoginActionPerformed
        // TODO add your handling code here:
      try {
            Connection c = Koneksi.getKoneksi();
            Statement s = c.createStatement();
            
            String sql = "SELECT * FROM tbl_staff WHERE username='" + LabelUsername.getText() + "' AND password='"+ LabelPassword.getText()+"'";

            ResultSet r = s.executeQuery(sql);
            
             if(r.next()){
                if(LabelUsername.getText().equals(r.getString("username"))&& LabelPassword.getText().equals(r.getString("password")))
                    JOptionPane.showMessageDialog(null, "Berhasil Login");
                    Menu4A Menu4A = new Menu4A();
                    Menu4A.setVisible(true);
                    dispose();
            }else {
                JOptionPane.showMessageDialog(null, "Username atau Password Salah");
            }

        }catch  (SQLException e){
            System.out.println("Error");
        }
    }//GEN-LAST:event_buttonLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField LabelPassword;
    private javax.swing.JTextField LabelUsername;
    private javax.swing.JLabel LoginStaff;
    private javax.swing.JLabel Password;
    private javax.swing.JLabel Username;
    private javax.swing.JButton buttonKembali;
    private javax.swing.JButton buttonLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel pww;
    // End of variables declaration//GEN-END:variables
}
