/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author BEELZEBUB
 */
package tiket.bioskop;
public class Menu4A extends javax.swing.JFrame {

    /**
     * Creates new form Menu4A
     */
    public Menu4A() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        Studio = new javax.swing.JButton();
        Pelanggan = new javax.swing.JButton();
        Film = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        StaffMode = new javax.swing.JLabel();
        Logout = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("CINEMA 256");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(420, 210, 220, 50);

        Studio.setFont(new java.awt.Font("Microsoft Tai Le", 1, 14)); // NOI18N
        Studio.setText("Studio");
        Studio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StudioActionPerformed(evt);
            }
        });
        getContentPane().add(Studio);
        Studio.setBounds(630, 350, 130, 130);

        Pelanggan.setFont(new java.awt.Font("Microsoft Tai Le", 1, 14)); // NOI18N
        Pelanggan.setText("Pelanggan");
        Pelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PelangganActionPerformed(evt);
            }
        });
        getContentPane().add(Pelanggan);
        Pelanggan.setBounds(470, 350, 130, 130);

        Film.setFont(new java.awt.Font("Microsoft Tai Le", 1, 14)); // NOI18N
        Film.setText("Film");
        Film.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FilmActionPerformed(evt);
            }
        });
        getContentPane().add(Film);
        Film.setBounds(310, 350, 130, 130);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Aset/logofix1.png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(410, 60, 250, 150);

        StaffMode.setFont(new java.awt.Font("Microsoft Tai Le", 1, 18)); // NOI18N
        StaffMode.setForeground(new java.awt.Color(255, 255, 255));
        StaffMode.setText("Staff Mode");
        getContentPane().add(StaffMode);
        StaffMode.setBounds(490, 280, 95, 24);

        Logout.setText("Logout");
        Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutActionPerformed(evt);
            }
        });
        getContentPane().add(Logout);
        Logout.setBounds(10, 20, 71, 25);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Aset/bgfix.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1070, 600);

        setBounds(0, 0, 1086, 639);
    }// </editor-fold>//GEN-END:initComponents

    private void FilmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FilmActionPerformed
        // TODO add your handling code here:
        Menu5 su=new Menu5();
        su.show();
        dispose();
    }//GEN-LAST:event_FilmActionPerformed

    private void LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutActionPerformed
        // TODO add your handling code here:
        Menu4 su=new Menu4();
        su.show();
        dispose();
    }//GEN-LAST:event_LogoutActionPerformed

    private void PelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PelangganActionPerformed
        // TODO add your handling code here:
        Menu6 su=new Menu6();
        su.show();
        dispose();
    }//GEN-LAST:event_PelangganActionPerformed

    private void StudioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StudioActionPerformed
        // TODO add your handling code here:
        Menu7 su=new Menu7();
        su.show();
        dispose();
    }//GEN-LAST:event_StudioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu4A.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu4A.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu4A.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu4A.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu4A().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Film;
    private javax.swing.JButton Logout;
    private javax.swing.JButton Pelanggan;
    private javax.swing.JLabel StaffMode;
    private javax.swing.JButton Studio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
