/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author BEELZEBUB
 */
package tiket.bioskop;

import java.awt.HeadlessException;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JToggleButton;
import javax.swing.table.DefaultTableModel;

public class Menu2 extends javax.swing.JFrame {

    /**
     * Creates new form Menu2
     */
    public Menu2() {
        initComponents();
        tampil_combo();
        tanggal(); 
        tampil_data();
        id_pesan_otomatis();
    }
    
    public void tampil_data(){
        DefaultTableModel tabel = new DefaultTableModel();
        tabel.addColumn("Judul Film");
        tabel.addColumn("Durasi Film");
        tabel.addColumn("Rating Usia");
        tabel.addColumn("Studio");
        try{
            java.sql.Connection conn=(java.sql.Connection)tiket.bioskop.Koneksi.getKoneksi();
            String sql = "SELECT judul_film,durasi_film,rating_usia,studio FROM tbl_film ";
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            ResultSet rs=pst.executeQuery(sql);
            while(rs.next())
            {
                tabel.addRow(new Object[]{
                rs.getString(1),
                rs.getString(2),
                rs.getString(3),
                rs.getString(4)});
        }jTable1.setModel(tabel);
        }catch (Exception e){
            
        }
    }
    
    public void hitung(){
        if (cbHari.getSelectedItem().equals("Pilih Hari")){
        txtHarga.setText("");
        } else {
        String jumlahTiketText = LabelJumlahTiket.getText();
        if (jumlahTiketText.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Mohon pilih kursi terlebih dahulu.");
        } else {
            int jumlahKursi = Integer.parseInt(jumlahTiketText);
            int totalHarga = 0;
            if (cbHari.getSelectedItem().equals("Senin") ||
                cbHari.getSelectedItem().equals("Selasa") ||
                cbHari.getSelectedItem().equals("Rabu") ||
                cbHari.getSelectedItem().equals("Kamis")) {
                totalHarga = jumlahKursi * 50000;
            } else if (cbHari.getSelectedItem().equals("Jumat")) {
                totalHarga = jumlahKursi * 60000;
            } else if (cbHari.getSelectedItem().equals("Sabtu") ||
                       cbHari.getSelectedItem().equals("Minggu")) {
                totalHarga = jumlahKursi * 70000;
            }
            txtHarga.setText(String.valueOf(totalHarga));
        }
        }
    }
    public void bersih(){
        LabelKursi.setText("");
        LabelJumlahTiket.setText("");
        txtHarga.setText("");
        txtidPesan.setText("");
        cbJamTayang.setSelectedItem("Pilih Jam");
        cbPilihFilm.setSelectedItem("Pilih Film");
        cbHari.setSelectedItem("Pilih Hari");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollBar1 = new javax.swing.JScrollBar();
        txtTanggal = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        LabelJumlahTiket = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        LabelKursi = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        txtHarga = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cbHari = new javax.swing.JComboBox<>();
        Hari = new javax.swing.JLabel();
        JumlahTiket = new javax.swing.JLabel();
        txtidPesan = new javax.swing.JTextField();
        NoTelp = new javax.swing.JLabel();
        Harga = new javax.swing.JLabel();
        Studio = new javax.swing.JLabel();
        PilihFilm = new javax.swing.JLabel();
        panel = new javax.swing.JPanel();
        A1 = new javax.swing.JButton();
        A2 = new javax.swing.JButton();
        A3 = new javax.swing.JButton();
        A4 = new javax.swing.JButton();
        A5 = new javax.swing.JButton();
        A6 = new javax.swing.JButton();
        B1 = new javax.swing.JButton();
        B2 = new javax.swing.JButton();
        B3 = new javax.swing.JButton();
        B4 = new javax.swing.JButton();
        B5 = new javax.swing.JButton();
        B6 = new javax.swing.JButton();
        C1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        C2 = new javax.swing.JButton();
        C3 = new javax.swing.JButton();
        C4 = new javax.swing.JButton();
        C5 = new javax.swing.JButton();
        C6 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        Pesan = new javax.swing.JButton();
        cbPilihFilm = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        kembali = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        cbJamTayang = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(500, 500));
        getContentPane().setLayout(null);

        txtTanggal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTanggal.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtTanggal.setEnabled(false);
        getContentPane().add(txtTanggal);
        txtTanggal.setBounds(490, 20, 120, 30);

        LabelJumlahTiket.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LabelJumlahTiket, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LabelJumlahTiket, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel4);
        jPanel4.setBounds(260, 360, 120, 30);

        LabelKursi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LabelKursi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LabelKursi, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel3);
        jPanel3.setBounds(260, 400, 120, 30);

        txtHarga.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtHarga, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtHarga, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(260, 440, 120, 30);

        jLabel2.setFont(new java.awt.Font("Microsoft Tai Le", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Tanggal");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(440, 20, 50, 30);

        cbHari.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Hari", "Senin", "Selasa", "Rabu", "Kamis", "Jumat", "Sabtu", "Minggu" }));
        cbHari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbHariActionPerformed(evt);
            }
        });
        getContentPane().add(cbHari);
        cbHari.setBounds(260, 320, 120, 30);

        Hari.setFont(new java.awt.Font("Microsoft Tai Le", 1, 12)); // NOI18N
        Hari.setForeground(new java.awt.Color(255, 255, 255));
        Hari.setText("Hari                          :");
        getContentPane().add(Hari);
        Hari.setBounds(150, 320, 120, 30);

        JumlahTiket.setFont(new java.awt.Font("Microsoft Tai Le", 1, 12)); // NOI18N
        JumlahTiket.setForeground(new java.awt.Color(255, 255, 255));
        JumlahTiket.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        JumlahTiket.setText("Jumlah Tiket          :");
        getContentPane().add(JumlahTiket);
        JumlahTiket.setBounds(150, 360, 110, 30);

        txtidPesan.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtidPesan.setEnabled(false);
        txtidPesan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidPesanActionPerformed(evt);
            }
        });
        txtidPesan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtidPesanKeyTyped(evt);
            }
        });
        getContentPane().add(txtidPesan);
        txtidPesan.setBounds(260, 200, 120, 30);

        NoTelp.setFont(new java.awt.Font("Microsoft Tai Le", 1, 12)); // NOI18N
        NoTelp.setForeground(new java.awt.Color(255, 255, 255));
        NoTelp.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        NoTelp.setText("ID Pesan                 :");
        getContentPane().add(NoTelp);
        NoTelp.setBounds(150, 200, 110, 30);

        Harga.setFont(new java.awt.Font("Microsoft Tai Le", 1, 12)); // NOI18N
        Harga.setForeground(new java.awt.Color(255, 255, 255));
        Harga.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Harga.setText("      Harga                       :");
        getContentPane().add(Harga);
        Harga.setBounds(130, 440, 130, 30);

        Studio.setFont(new java.awt.Font("Microsoft Tai Le", 1, 12)); // NOI18N
        Studio.setForeground(new java.awt.Color(255, 255, 255));
        Studio.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Studio.setText("Kursi                        :");
        getContentPane().add(Studio);
        Studio.setBounds(150, 400, 110, 30);

        PilihFilm.setFont(new java.awt.Font("Microsoft Tai Le", 1, 12)); // NOI18N
        PilihFilm.setForeground(new java.awt.Color(255, 255, 255));
        PilihFilm.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        PilihFilm.setText("Pilih Film                 :");
        getContentPane().add(PilihFilm);
        PilihFilm.setBounds(150, 280, 110, 30);

        panel.setBackground(new java.awt.Color(0, 0, 153));
        panel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panel.setLayout(null);

        A1.setText("A1");
        A1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A1ActionPerformed(evt);
            }
        });
        panel.add(A1);
        A1.setBounds(30, 30, 50, 50);

        A2.setText("A2");
        A2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A2ActionPerformed(evt);
            }
        });
        panel.add(A2);
        A2.setBounds(80, 30, 50, 50);

        A3.setText("A3");
        A3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A3ActionPerformed(evt);
            }
        });
        panel.add(A3);
        A3.setBounds(130, 30, 50, 50);

        A4.setText("A4");
        A4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A4ActionPerformed(evt);
            }
        });
        panel.add(A4);
        A4.setBounds(240, 30, 50, 50);

        A5.setText("A5");
        A5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A5ActionPerformed(evt);
            }
        });
        panel.add(A5);
        A5.setBounds(290, 30, 50, 50);

        A6.setText("A6");
        A6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A6ActionPerformed(evt);
            }
        });
        panel.add(A6);
        A6.setBounds(340, 30, 50, 50);

        B1.setText("B1");
        B1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B1ActionPerformed(evt);
            }
        });
        panel.add(B1);
        B1.setBounds(30, 80, 50, 50);

        B2.setText("B2");
        B2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B2ActionPerformed(evt);
            }
        });
        panel.add(B2);
        B2.setBounds(80, 80, 50, 50);

        B3.setText("B3");
        B3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B3ActionPerformed(evt);
            }
        });
        panel.add(B3);
        B3.setBounds(130, 80, 50, 50);

        B4.setText("B4");
        B4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B4ActionPerformed(evt);
            }
        });
        panel.add(B4);
        B4.setBounds(240, 80, 50, 50);

        B5.setText("B5");
        B5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B5ActionPerformed(evt);
            }
        });
        panel.add(B5);
        B5.setBounds(290, 80, 50, 50);

        B6.setText("B6");
        B6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B6ActionPerformed(evt);
            }
        });
        panel.add(B6);
        B6.setBounds(340, 80, 50, 50);

        C1.setText("C1");
        C1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C1ActionPerformed(evt);
            }
        });
        panel.add(C1);
        C1.setBounds(30, 130, 50, 50);

        jPanel2.setBackground(new java.awt.Color(153, 153, 255));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("LAYAR");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        panel.add(jPanel2);
        jPanel2.setBounds(30, 210, 400, 40);

        C2.setText("C2");
        C2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C2ActionPerformed(evt);
            }
        });
        panel.add(C2);
        C2.setBounds(80, 130, 50, 50);

        C3.setText("C3");
        C3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C3ActionPerformed(evt);
            }
        });
        panel.add(C3);
        C3.setBounds(130, 130, 50, 50);

        C4.setText("C4");
        C4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C4ActionPerformed(evt);
            }
        });
        panel.add(C4);
        C4.setBounds(240, 130, 50, 50);

        C5.setText("C5");
        C5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C5ActionPerformed(evt);
            }
        });
        panel.add(C5);
        C5.setBounds(290, 130, 50, 50);

        C6.setText("C6");
        C6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C6ActionPerformed(evt);
            }
        });
        panel.add(C6);
        C6.setBounds(340, 130, 50, 50);

        getContentPane().add(panel);
        panel.setBounds(470, 300, 460, 270);

        jButton1.setText("Hapus");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(290, 510, 90, 30);

        Pesan.setText("Pesan");
        Pesan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PesanActionPerformed(evt);
            }
        });
        getContentPane().add(Pesan);
        Pesan.setBounds(150, 510, 90, 30);

        cbPilihFilm.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Film" }));
        cbPilihFilm.setToolTipText("");
        cbPilihFilm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbPilihFilmActionPerformed(evt);
            }
        });
        getContentPane().add(cbPilihFilm);
        cbPilihFilm.setBounds(260, 280, 120, 30);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Judul Film", "Durasi Film", "Rating Usia", "Studio"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(470, 160, 460, 100);

        kembali.setText("Kembali");
        kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kembaliActionPerformed(evt);
            }
        });
        getContentPane().add(kembali);
        kembali.setBounds(10, 20, 77, 25);

        jLabel3.setFont(new java.awt.Font("Microsoft Tai Le", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Jam Tayang            :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(150, 250, 110, 17);

        cbJamTayang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Jam", "12 PM", "03 PM", "06 PM", "08 PM" }));
        cbJamTayang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbJamTayangActionPerformed(evt);
            }
        });
        getContentPane().add(cbJamTayang);
        cbJamTayang.setBounds(260, 240, 120, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Aset/bgfix.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1070, 600);

        setBounds(0, 0, 1086, 639);
    }// </editor-fold>//GEN-END:initComponents

    public void jumKursi(){
        String jumlahKursi = LabelKursi.getText();
        String[] data = jumlahKursi.split(",");
        int jumlahData = data.length;
        LabelJumlahTiket.setText(Integer.toString(jumlahData));
    }
    public void id_pesan_otomatis() {
    try {
        // Mendapatkan koneksi dari kelas Koneksi
            Connection connection = tiket.bioskop.Koneksi.getKoneksi();
            String query = "SELECT * FROM tbl_pesan ORDER BY id_pesan DESC";
            PreparedStatement statement = connection.prepareStatement(query);
            ResultSet resultSet = statement.executeQuery();
            if (resultSet.next()) {
                String id = resultSet.getString(1);
                int nextId = Integer.parseInt(id.substring(1)) + 1;
                String AN = String.format("%03d", nextId);
                txtidPesan.setText("P" + AN);
            } else {
                txtidPesan.setText("P001");
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
    
    private void kembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembaliActionPerformed
        // TODO add your handling code here:
        Menu1 su=new Menu1();
        su.show();
        dispose();
    }//GEN-LAST:event_kembaliActionPerformed

    public void tanggal () {
        Date ys = new Date();
        SimpleDateFormat s =  new SimpleDateFormat("yyyy-MM-dd");
        txtTanggal.setText(s.format(ys));
    }
    
    public void tampil_combo(){
        try{
            java.sql.Connection conn=(java.sql.Connection)tiket.bioskop.Koneksi.getKoneksi();
            String sql = "SELECT *FROM tbl_film";
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            ResultSet rs=pst.executeQuery(sql);
            
            while(rs.next()){
                cbPilihFilm.addItem(rs.getString("judul_film"));
            }
            
            rs.last();
            int jumlahdata = rs.getRow();
            rs.first();
        }catch(Exception e){
            
        }
    }
    private void PesanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PesanActionPerformed
        // TODO add your handling code here:
        try {
            String idPesan = txtidPesan.getText();
            String jamTayang = cbJamTayang.getSelectedItem().toString();
            String film = cbPilihFilm.getSelectedItem().toString();
            String hari = cbHari.getSelectedItem().toString();
            String jumlahTiket = LabelJumlahTiket.getText();
            String kursi = LabelKursi.getText();
            String harga = txtHarga.getText();
            String tanggal = txtTanggal.getText();
            if (idPesan.isEmpty() || jamTayang.isEmpty() || film.isEmpty() || hari.isEmpty() || jumlahTiket.isEmpty() || kursi.isEmpty() || harga.isEmpty() || tanggal.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Harap lengkapi semua field");
            } else {
                java.sql.Connection conn = tiket.bioskop.Koneksi.getKoneksi();
                String getStudio = "SELECT studio FROM tbl_film WHERE judul_film = ?";
                java.sql.PreparedStatement pstStudio = conn.prepareStatement(getStudio);
                pstStudio.setString(1, film);
                java.sql.ResultSet rsStudio = pstStudio.executeQuery();

                String studio = "";
                if (rsStudio.next()) {
                    studio = rsStudio.getString("studio");
                }
                String sql = "INSERT INTO tbl_pesan (id_pesan, jam_tayang, film, hari, jumlah_tiket, kursi, harga, tanggal, Studio_F) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)";
                java.sql.PreparedStatement pst = conn.prepareStatement(sql);
                pst.setString(1, idPesan);
                pst.setString(2, jamTayang);
                pst.setString(3, film);
                pst.setString(4, hari);
                pst.setString(5, jumlahTiket);
                pst.setString(6, kursi);
                pst.setString(7, harga);
                pst.setString(8, tanggal);
                pst.setString(9, studio);

                pst.execute();
                JOptionPane.showMessageDialog(null, "Berhasil disimpan");
                tampil_data();
                bersih();
                Menu3 su = new Menu3();
                su.show();
                dispose();
            }
        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(null, "Gagal disimpan");
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_PesanActionPerformed

    private void cbPilihFilmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbPilihFilmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbPilihFilmActionPerformed

    private void txtidPesanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidPesanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidPesanActionPerformed

    private void cbHariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbHariActionPerformed
        // TODO add your handling code here:
        if(cbHari.getSelectedItem().equals("Pilih Hari")){
            txtHarga.setText(" ");
        }else if (cbHari.getSelectedItem().equals("Senin")){
            hitung();
        }else if (cbHari.getSelectedItem().equals("Selasa")){
            hitung();
        }else if (cbHari.getSelectedItem().equals("Rabu")){
            hitung();
        }else if (cbHari.getSelectedItem().equals("Kamis")){
            hitung();
        }else if (cbHari.getSelectedItem().equals("Jumat")){
            hitung();
        }else if (cbHari.getSelectedItem().equals("Sabtu")){
            hitung();
        }else if (cbHari.getSelectedItem().equals("Minggu")){
            hitung();
        }
    }//GEN-LAST:event_cbHariActionPerformed

    private void A1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A1ActionPerformed
        // TODO add your handling code here:
        boolean A1Selected = false;
        if (!A1Selected) {
            String buttonText = A1.getText();
            String currentText = LabelKursi.getText();
            String updatedText = currentText + buttonText + ",";
            LabelKursi.setText(updatedText);
            A1Selected = true;
            A1.setEnabled(false);
        }else{
            String buttonText = A1.getText();
            String currentText = LabelKursi.getText();
            String updatedText = currentText.replace(buttonText + ",", "");
            LabelKursi.setText(updatedText);
            A1Selected = false;
        }jumKursi();
        hitung();
    }//GEN-LAST:event_A1ActionPerformed

    private void A2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A2ActionPerformed
        // TODO add your handling code here:
        boolean A2Selected = false;
        if (!A2Selected) {
            String buttonText = A2.getText();
            String currentText = LabelKursi.getText();
            String updatedText = currentText + buttonText + ",";
            LabelKursi.setText(updatedText);
            A2Selected = true;
            A2.setEnabled(false);
        }else{
            String buttonText = A2.getText();
            String currentText = LabelKursi.getText();
            String updatedText = currentText.replace(buttonText + ",", "");
            LabelKursi.setText(updatedText);
            A2Selected = false;
        } jumKursi();
        hitung();
    }//GEN-LAST:event_A2ActionPerformed

    private void A3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A3ActionPerformed
        // TODO add your handling code here:
        boolean A3Selected = false;
        if (!A3Selected) {
            String buttonText = A3.getText();
            String currentText = LabelKursi.getText();
            String updatedText = currentText + buttonText + ",";
            LabelKursi.setText(updatedText);
            A3Selected = true;
            A3.setEnabled(false);
        }else{
            String buttonText = A3.getText();
            String currentText = LabelKursi.getText();
            String updatedText = currentText.replace(buttonText + ",", "");
            LabelKursi.setText(updatedText);
            A3Selected = false;
        } jumKursi();
        hitung();
    }//GEN-LAST:event_A3ActionPerformed

    private void A4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A4ActionPerformed
        // TODO add your handling code here:
        boolean A4Selected = false;
        if (!A4Selected) {
            String buttonText = A4.getText();
            String currentText = LabelKursi.getText();
            String updatedText = currentText + buttonText + ",";
            LabelKursi.setText(updatedText);
            A4Selected = true;
            A4.setEnabled(false);
        }else{
            String buttonText = A4.getText();
            String currentText = LabelKursi.getText();
            String updatedText = currentText.replace(buttonText + ",", "");
            LabelKursi.setText(updatedText);
            A4Selected = false;
        } jumKursi();
        hitung();
    }//GEN-LAST:event_A4ActionPerformed

    private void A5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A5ActionPerformed
        // TODO add your handling code here:
        boolean A5Selected = false;
        if (!A5Selected) {
            String buttonText = A5.getText();
            String currentText = LabelKursi.getText();
            String updatedText = currentText + buttonText + ",";
            LabelKursi.setText(updatedText);
            A5Selected = true;
            A5.setEnabled(false);
        }else{
            String buttonText = A5.getText();
            String currentText = LabelKursi.getText();
            String updatedText = currentText.replace(buttonText + ",", "");
            LabelKursi.setText(updatedText);
            A5Selected = false;
        } jumKursi();
        hitung();
    }//GEN-LAST:event_A5ActionPerformed

    private void B3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B3ActionPerformed
        // TODO add your handling code here:
        boolean B3Selected = false;
        if (!B3Selected) {
            String buttonText = B3.getText();
            String currentText = LabelKursi.getText();
            String updatedText = currentText + buttonText + ",";
            LabelKursi.setText(updatedText);
            B3Selected = true;
            B3.setEnabled(false);
        }else{
            String buttonText = B3.getText();
            String currentText = LabelKursi.getText();
            String updatedText = currentText.replace(buttonText + ",", "");
            LabelKursi.setText(updatedText);
            B3Selected = false;
        } jumKursi();
        hitung();
    }//GEN-LAST:event_B3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        bersih();
        A1.setEnabled(true);
        A2.setEnabled(true);
        A3.setEnabled(true);
        A4.setEnabled(true);
        A5.setEnabled(true);
        A6.setEnabled(true);
        B1.setEnabled(true);
        B2.setEnabled(true);
        B3.setEnabled(true);
        B4.setEnabled(true);
        B5.setEnabled(true);
        B6.setEnabled(true);
        C1.setEnabled(true);
        C2.setEnabled(true);
        C3.setEnabled(true);
        C4.setEnabled(true);
        C5.setEnabled(true);
        C6.setEnabled(true);
        id_pesan_otomatis();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void B1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B1ActionPerformed
        // TODO add your handling code here:
        boolean B1Selected = false;
        if (!B1Selected) {
            String buttonText = B1.getText();
            String currentText = LabelKursi.getText();
            String updatedText = currentText + buttonText + ",";
            LabelKursi.setText(updatedText);
            B1Selected = true;
            B1.setEnabled(false);
        }else{
            String buttonText = B1.getText();
            String currentText = LabelKursi.getText();
            String updatedText = currentText.replace(buttonText + ",", "");
            LabelKursi.setText(updatedText);
            B1Selected = false;
        } jumKursi();
        hitung();
    }//GEN-LAST:event_B1ActionPerformed

    private void B2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B2ActionPerformed
        // TODO add your handling code here:
        boolean B2Selected = false;
        if (!B2Selected) {
            String buttonText = B2.getText();
            String currentText = LabelKursi.getText();
            String updatedText = currentText + buttonText + ",";
            LabelKursi.setText(updatedText);
            B2Selected = true;
            B2.setEnabled(false);
        }else{
            String buttonText = B2.getText();
            String currentText = LabelKursi.getText();
            String updatedText = currentText.replace(buttonText + ",", "");
            LabelKursi.setText(updatedText);
            B2Selected = false;
        } jumKursi();
        hitung();
    }//GEN-LAST:event_B2ActionPerformed

    private void B4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B4ActionPerformed
        // TODO add your handling code here:
        boolean B4Selected = false;
        if (!B4Selected) {
            String buttonText = B4.getText();
            String currentText = LabelKursi.getText();
            String updatedText = currentText + buttonText + ",";
            LabelKursi.setText(updatedText);
            B4Selected = true;
            B4.setEnabled(false);
        }else{
            String buttonText = B4.getText();
            String currentText = LabelKursi.getText();
            String updatedText = currentText.replace(buttonText + ",", "");
            LabelKursi.setText(updatedText);
            B4Selected = false;
        } jumKursi();
        hitung();
    }//GEN-LAST:event_B4ActionPerformed

    private void B5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B5ActionPerformed
        // TODO add your handling code here:
        boolean B5Selected = false;
        if (!B5Selected) {
            String buttonText = B5.getText();
            String currentText = LabelKursi.getText();
            String updatedText = currentText + buttonText + ",";
            LabelKursi.setText(updatedText);
            B5Selected = true;
            B5.setEnabled(false);
        }else{
            String buttonText = B5.getText();
            String currentText = LabelKursi.getText();
            String updatedText = currentText.replace(buttonText + ",", "");
            LabelKursi.setText(updatedText);
            B5Selected = false;
        } jumKursi();
        hitung();
    }//GEN-LAST:event_B5ActionPerformed

    private void A6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A6ActionPerformed
        // TODO add your handling code here:
        boolean A6Selected = false;
        if (!A6Selected) {
            String buttonText = A6.getText();
            String currentText = LabelKursi.getText();
            String updatedText = currentText + buttonText + ",";
            LabelKursi.setText(updatedText);
            A6Selected = true;
            A6.setEnabled(false);
        }else{
            String buttonText = A6.getText();
            String currentText = LabelKursi.getText();
            String updatedText = currentText.replace(buttonText + ",", "");
            LabelKursi.setText(updatedText);
            A6Selected = false;
        } jumKursi();
        hitung();
    }//GEN-LAST:event_A6ActionPerformed

    private void B6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B6ActionPerformed
        // TODO add your handling code here:
        boolean B6Selected = false;
        if (!B6Selected) {
            String buttonText = B6.getText();
            String currentText = LabelKursi.getText();
            String updatedText = currentText + buttonText + ",";
            LabelKursi.setText(updatedText);
            B6Selected = true;
            B6.setEnabled(false);
        }else{
            String buttonText = B6.getText();
            String currentText = LabelKursi.getText();
            String updatedText = currentText.replace(buttonText + ",", "");
            LabelKursi.setText(updatedText);
            B6Selected = false;
        } jumKursi();
        hitung();
    }//GEN-LAST:event_B6ActionPerformed

    private void C1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C1ActionPerformed
        // TODO add your handling code here:
        boolean C1Selected = false;
        if (!C1Selected) {
            String buttonText = C1.getText();
            String currentText = LabelKursi.getText();
            String updatedText = currentText + buttonText + ",";
            LabelKursi.setText(updatedText);
            C1Selected = true;
            C1.setEnabled(false);
        }else{
            String buttonText = C1.getText();
            String currentText = LabelKursi.getText();
            String updatedText = currentText.replace(buttonText + ",", "");
            LabelKursi.setText(updatedText);
            C1Selected = false;
        } jumKursi();
        hitung();
    }//GEN-LAST:event_C1ActionPerformed

    private void C2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C2ActionPerformed
        // TODO add your handling code here:
        boolean C2Selected = false;
        if (!C2Selected) {
            String buttonText = C2.getText();
            String currentText = LabelKursi.getText();
            String updatedText = currentText + buttonText + ",";
            LabelKursi.setText(updatedText);
            C2Selected = true;
            C2.setEnabled(false);
        }else{
            String buttonText = C2.getText();
            String currentText = LabelKursi.getText();
            String updatedText = currentText.replace(buttonText + ",", "");
            LabelKursi.setText(updatedText);
            C2Selected = false;
        } jumKursi();
        hitung();
    }//GEN-LAST:event_C2ActionPerformed

    private void C3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C3ActionPerformed
        // TODO add your handling code here:
        boolean C3Selected = false;
        if (!C3Selected) {
            String buttonText = C3.getText();
            String currentText = LabelKursi.getText();
            String updatedText = currentText + buttonText + ",";
            LabelKursi.setText(updatedText);
            C3Selected = true;
            C3.setEnabled(false);
        }else{
            String buttonText = C3.getText();
            String currentText = LabelKursi.getText();
            String updatedText = currentText.replace(buttonText + ",", "");
            LabelKursi.setText(updatedText);
            C3Selected = false;
        } jumKursi();
        hitung();
    }//GEN-LAST:event_C3ActionPerformed

    private void C4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C4ActionPerformed
        // TODO add your handling code here:
        boolean C4Selected = false;
        if (!C4Selected) {
            String buttonText = C4.getText();
            String currentText = LabelKursi.getText();
            String updatedText = currentText + buttonText + ",";
            LabelKursi.setText(updatedText);
            C4Selected = true;
            C4.setEnabled(false);
        }else{
            String buttonText = C4.getText();
            String currentText = LabelKursi.getText();
            String updatedText = currentText.replace(buttonText + ",", "");
            LabelKursi.setText(updatedText);
            C4Selected = false;
        } jumKursi();
        hitung();
    }//GEN-LAST:event_C4ActionPerformed

    private void C5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C5ActionPerformed
        // TODO add your handling code here:
        boolean C5Selected = false;
        if (!C5Selected) {
            String buttonText = C5.getText();
            String currentText = LabelKursi.getText();
            String updatedText = currentText + buttonText + ",";
            LabelKursi.setText(updatedText);
            C5Selected = true;
            C5.setEnabled(false);
        }else{
            String buttonText = C5.getText();
            String currentText = LabelKursi.getText();
            String updatedText = currentText.replace(buttonText + ",", "");
            LabelKursi.setText(updatedText);
            C5Selected = false;
        } jumKursi();
        hitung();
    }//GEN-LAST:event_C5ActionPerformed

    private void C6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C6ActionPerformed
        // TODO add your handling code here:
        boolean C6Selected = false;
        if (!C6Selected) {
            String buttonText = C6.getText();
            String currentText = LabelKursi.getText();
            String updatedText = currentText + buttonText + ",";
            LabelKursi.setText(updatedText);
            C6Selected = true;
            C6.setEnabled(false);
        }else{
            String buttonText = C6.getText();
            String currentText = LabelKursi.getText();
            String updatedText = currentText.replace(buttonText + ",", "");
            LabelKursi.setText(updatedText);
            C6Selected = false;
        } jumKursi();
        hitung();
    }//GEN-LAST:event_C6ActionPerformed

    private void cbJamTayangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbJamTayangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbJamTayangActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int selectedRow = jTable1.getSelectedRow();
        if (selectedRow != -1) {
            String film = jTable1.getValueAt(selectedRow, 0).toString();
            cbPilihFilm.setSelectedItem(film);
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void txtidPesanKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtidPesanKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidPesanKeyTyped

    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu2().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton A1;
    private javax.swing.JButton A2;
    private javax.swing.JButton A3;
    private javax.swing.JButton A4;
    private javax.swing.JButton A5;
    private javax.swing.JButton A6;
    private javax.swing.JButton B1;
    private javax.swing.JButton B2;
    private javax.swing.JButton B3;
    private javax.swing.JButton B4;
    private javax.swing.JButton B5;
    private javax.swing.JButton B6;
    private javax.swing.JButton C1;
    private javax.swing.JButton C2;
    private javax.swing.JButton C3;
    private javax.swing.JButton C4;
    private javax.swing.JButton C5;
    private javax.swing.JButton C6;
    private javax.swing.JLabel Harga;
    private javax.swing.JLabel Hari;
    private javax.swing.JLabel JumlahTiket;
    private javax.swing.JLabel LabelJumlahTiket;
    private javax.swing.JLabel LabelKursi;
    private javax.swing.JLabel NoTelp;
    private javax.swing.JButton Pesan;
    private javax.swing.JLabel PilihFilm;
    private javax.swing.JLabel Studio;
    private javax.swing.JComboBox<String> cbHari;
    private javax.swing.JComboBox<String> cbJamTayang;
    private javax.swing.JComboBox<String> cbPilihFilm;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton kembali;
    private javax.swing.JPanel panel;
    private javax.swing.JLabel txtHarga;
    private javax.swing.JTextField txtTanggal;
    public javax.swing.JTextField txtidPesan;
    // End of variables declaration//GEN-END:variables
}
