/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author BEELZEBUB
 */
package tiket.bioskop;

import java.awt.HeadlessException;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class Menu6 extends javax.swing.JFrame {

    /**
     * Creates new form Menu6
     */
    public Menu6() {
        initComponents();
        tampil_data();
        cbTampil();
    }
    
    public void bersih(){
        txtIDPesan.setText(null);
        cbJam.setSelectedItem(null);
        cbFilm.setSelectedItem(null);
        cbHari.setSelectedItem(null);
        txtJumlah.setText(null);
        txtKursi.setText(null);
        txtHarga.setText(null);
        txtTanggal.setText(null);
        txtStudio.setText(null);
    }
    
    public void cbTampil(){
        try{
            java.sql.Connection conn=(java.sql.Connection)tiket.bioskop.Koneksi.getKoneksi();
            String sql = "SELECT *FROM tbl_film";
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            ResultSet rs=pst.executeQuery(sql);
            
            while(rs.next()){
                cbFilm.addItem(rs.getString("judul_film"));
            }
            
            rs.last();
            int jumlahdata = rs.getRow();
            rs.first();
        }catch(Exception e){
            
        }
    }

    public void tampil_data(){
        DefaultTableModel tabel = new DefaultTableModel();
        tabel.addColumn("ID Pesan");
        tabel.addColumn("Jam Tayang");
        tabel.addColumn("Film");
        tabel.addColumn("Hari");
        tabel.addColumn("Jumlah Tiket");
        tabel.addColumn("kursi");
        tabel.addColumn("Harga");
        tabel.addColumn("Tanggal");
        tabel.addColumn("Studio");
        try{
            java.sql.Connection conn=(java.sql.Connection)tiket.bioskop.Koneksi.getKoneksi();
            String sql = "SELECT * FROM tbl_pesan ";
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            ResultSet rs=pst.executeQuery(sql);
            while(rs.next())
            {
                tabel.addRow(new Object[]{
                rs.getString(1),
                rs.getString(2),
                rs.getString(3),
                rs.getString(4),
                rs.getString(5),
                rs.getString(6),
                rs.getString(7),
                rs.getString(8),
                rs.getString(9)});
        }jTable1.setModel(tabel);
        }catch (Exception e){
            
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtIDPesan = new javax.swing.JTextField();
        txtKursi = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtJumlah = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtHarga = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtTanggal = new javax.swing.JTextField();
        txtStudio = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        cbFilm = new javax.swing.JComboBox<>();
        cbJam = new javax.swing.JComboBox<>();
        cbHari = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jButton1.setText("Kembali");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(10, 10, 77, 25);

        jPanel1.setBackground(new java.awt.Color(0, 0, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID Pesan", "Jam Tayang", "Film", "Hari", "Jumlah Tiket", "Kursi", "Harga", "Tanggal", "Studio"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 310, 630, 110));

        jButton4.setText("Hapus");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 270, 80, 30));

        jLabel7.setFont(new java.awt.Font("Microsoft Tai Le", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Film                     :");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 130, 30));

        jLabel6.setFont(new java.awt.Font("Microsoft Tai Le", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Jam Tayang        :");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 130, 30));

        jLabel5.setFont(new java.awt.Font("Microsoft Tai Le", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("ID Pesan              :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 130, 30));

        txtIDPesan.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtIDPesan.setEnabled(false);
        txtIDPesan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDPesanActionPerformed(evt);
            }
        });
        jPanel1.add(txtIDPesan, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, 100, 30));

        txtKursi.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtKursi.setEnabled(false);
        txtKursi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKursiActionPerformed(evt);
            }
        });
        jPanel1.add(txtKursi, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 100, 100, 30));

        jLabel9.setFont(new java.awt.Font("Microsoft Tai Le", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Kursi           :");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 100, 90, 30));

        txtJumlah.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtJumlah.setEnabled(false);
        txtJumlah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJumlahActionPerformed(evt);
            }
        });
        jPanel1.add(txtJumlah, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 60, 100, 30));

        jLabel8.setFont(new java.awt.Font("Microsoft Tai Le", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Jumlah        :");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 60, 90, 30));

        jLabel4.setFont(new java.awt.Font("Microsoft Tai Le", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Hari                     :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 120, 30));

        jLabel10.setFont(new java.awt.Font("Microsoft Tai Le", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Harga        :");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 140, 80, 30));

        txtHarga.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtHarga.setEnabled(false);
        txtHarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHargaActionPerformed(evt);
            }
        });
        jPanel1.add(txtHarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 140, 100, 30));

        jLabel11.setFont(new java.awt.Font("Microsoft Tai Le", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Tanggal     :");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 180, 80, 30));

        txtTanggal.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtTanggal.setEnabled(false);
        txtTanggal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTanggalActionPerformed(evt);
            }
        });
        jPanel1.add(txtTanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 180, 100, 30));

        txtStudio.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtStudio.setEnabled(false);
        txtStudio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStudioActionPerformed(evt);
            }
        });
        jPanel1.add(txtStudio, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, 100, 30));

        jLabel12.setFont(new java.awt.Font("Microsoft Tai Le", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Studio                 :");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, 120, 30));

        cbFilm.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Film" }));
        jPanel1.add(cbFilm, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, 100, 30));

        cbJam.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Jam", "12 PM", "03 PM", "06 PM", "08 PM" }));
        jPanel1.add(cbJam, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, 100, 30));

        cbHari.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Hari", "Senin", "Selasa", "Rabu", "Kamis", "Jumat", "Sabtu", "Minggu" }));
        jPanel1.add(cbHari, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, 100, 30));

        jLabel2.setFont(new java.awt.Font("Microsoft Tai Le", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Staff Mode : Pemesanan");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 290, -1));

        getContentPane().add(jPanel1);
        jPanel1.setBounds(220, 70, 650, 460);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Aset/bgfix.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1070, 600);

        setBounds(0, 0, 1086, 639);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Menu4A su=new Menu4A();
        su.show();
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtIDPesanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDPesanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDPesanActionPerformed

    private void txtJumlahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJumlahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJumlahActionPerformed

    private void txtKursiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKursiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKursiActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        try {
    String noTelp = txtIDPesan.getText();
    
    if (noTelp.isEmpty()) {
        JOptionPane.showMessageDialog(null, "ID Pesan tidak boleh kosong");
    } else {
        java.sql.Connection conn = (java.sql.Connection) tiket.bioskop.Koneksi.getKoneksi();
        String sql = "DELETE FROM tbl_pesan WHERE id_pesan = ?";
        java.sql.PreparedStatement pst = conn.prepareStatement(sql);
        pst.setString(1, noTelp);
        int result = pst.executeUpdate();
        
        if (result > 0) {
            JOptionPane.showMessageDialog(null, "Data berhasil dihapus");
            tampil_data();
            bersih();
        } else {
            JOptionPane.showMessageDialog(null, "Gagal menghapus data");
        }
    }
} catch (Exception e) {
    JOptionPane.showMessageDialog(null, "Proses Penghapusan Gagal");
    System.out.println(e.getMessage());
}

    }//GEN-LAST:event_jButton4ActionPerformed

    private void txtHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHargaActionPerformed

    private void txtTanggalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTanggalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTanggalActionPerformed

    private void txtStudioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStudioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStudioActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:                                   
    int selectedRow = jTable1.getSelectedRow();
    if (selectedRow != -1) {
        // Ambil nilai dari kolom-kolom yang sesuai dari model tabel
        String noTelp = jTable1.getValueAt(selectedRow, 0).toString();
        String jamTayang = jTable1.getValueAt(selectedRow, 1).toString();
        String film = jTable1.getValueAt(selectedRow, 2).toString();
        String hari = jTable1.getValueAt(selectedRow, 3).toString();
        String jumlah = jTable1.getValueAt(selectedRow, 4).toString();
        String kursi = jTable1.getValueAt(selectedRow, 5).toString();
        String harga = jTable1.getValueAt(selectedRow, 6).toString();
        String tanggal = jTable1.getValueAt(selectedRow, 7).toString();
        String studio = jTable1.getValueAt(selectedRow, 8).toString();

        // Mengatur nilai ke label dan combo box yang sesuai
        txtIDPesan.setText(noTelp);
        cbJam.setSelectedItem(jamTayang);
        cbFilm.setSelectedItem(film);
        cbHari.setSelectedItem(hari);
        txtJumlah.setText(jumlah);
        txtKursi.setText(kursi);
        txtHarga.setText(harga);
        txtTanggal.setText(tanggal);
        txtStudio.setText(studio);
    }


    }//GEN-LAST:event_jTable1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu6().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbFilm;
    private javax.swing.JComboBox<String> cbHari;
    private javax.swing.JComboBox<String> cbJam;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtHarga;
    private javax.swing.JTextField txtIDPesan;
    private javax.swing.JTextField txtJumlah;
    private javax.swing.JTextField txtKursi;
    private javax.swing.JTextField txtStudio;
    private javax.swing.JTextField txtTanggal;
    // End of variables declaration//GEN-END:variables
}
