/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author BEELZEBUB
 */
package tiket.bioskop;
public class Menu1 extends javax.swing.JFrame {

    /**
     * Creates new form Menu1
     */
    public Menu1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        PesanTiket = new javax.swing.JButton();
        Staff = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        Poster3 = new javax.swing.JLabel();
        Judul3 = new javax.swing.JLabel();
        Poster1 = new javax.swing.JLabel();
        Judul1 = new javax.swing.JLabel();
        Poster2 = new javax.swing.JLabel();
        Judul2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Judul4 = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(500, 500));
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("CINEMA 256");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(210, 280, 220, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Aset/logofix1.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(190, 110, 260, 180);

        PesanTiket.setFont(new java.awt.Font("Microsoft Tai Le", 1, 14)); // NOI18N
        PesanTiket.setText("Staff");
        PesanTiket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PesanTiketActionPerformed(evt);
            }
        });
        getContentPane().add(PesanTiket);
        PesanTiket.setBounds(340, 370, 120, 50);

        Staff.setFont(new java.awt.Font("Microsoft Tai Le", 1, 14)); // NOI18N
        Staff.setText("Pesan Tiket");
        Staff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StaffActionPerformed(evt);
            }
        });
        getContentPane().add(Staff);
        Staff.setBounds(170, 370, 120, 50);

        jPanel1.setBackground(new java.awt.Color(0, 102, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel1.setForeground(new java.awt.Color(0, 0, 255));

        Poster3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Aset/3.png"))); // NOI18N

        Judul3.setFont(new java.awt.Font("Lucida Fax", 1, 12)); // NOI18N
        Judul3.setForeground(new java.awt.Color(255, 255, 255));
        Judul3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Judul3.setText("Spider-Man");

        Poster1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Aset/1.png"))); // NOI18N

        Judul1.setFont(new java.awt.Font("Lucida Fax", 1, 12)); // NOI18N
        Judul1.setForeground(new java.awt.Color(255, 255, 255));
        Judul1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Judul1.setText("The Little Mermaid");

        Poster2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Aset/2.png"))); // NOI18N

        Judul2.setFont(new java.awt.Font("Lucida Fax", 1, 12)); // NOI18N
        Judul2.setForeground(new java.awt.Color(255, 255, 255));
        Judul2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Judul2.setText("Fast X");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Aset/The Flash.png"))); // NOI18N

        Judul4.setFont(new java.awt.Font("Lucida Fax", 1, 12)); // NOI18N
        Judul4.setForeground(new java.awt.Color(255, 255, 255));
        Judul4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Judul4.setText("The Flash");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Judul2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Poster2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Poster3, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Judul3, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Poster1)
                    .addComponent(jLabel4)
                    .addComponent(Judul1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Judul4, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Judul3)
                    .addComponent(Judul1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Poster3)
                    .addComponent(Poster1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Judul2)
                    .addComponent(Judul4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Poster2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        Poster2.getAccessibleContext().setAccessibleDescription("");

        getContentPane().add(jPanel1);
        jPanel1.setBounds(650, 30, 400, 540);

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Aset/bgfix.png"))); // NOI18N
        getContentPane().add(Background);
        Background.setBounds(-3, -4, 1070, 600);

        setBounds(0, 0, 1086, 639);
    }// </editor-fold>//GEN-END:initComponents

    private void StaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StaffActionPerformed
        // TODO add your handling code here:
        Menu2 su=new Menu2();
        su.show();
        dispose();
    }//GEN-LAST:event_StaffActionPerformed

    private void PesanTiketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PesanTiketActionPerformed
        // TODO add your handling code here:
        Menu4 su=new Menu4();
        su.show();
        dispose();
    }//GEN-LAST:event_PesanTiketActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JLabel Judul1;
    private javax.swing.JLabel Judul2;
    private javax.swing.JLabel Judul3;
    private javax.swing.JLabel Judul4;
    private javax.swing.JButton PesanTiket;
    private javax.swing.JLabel Poster1;
    private javax.swing.JLabel Poster2;
    private javax.swing.JLabel Poster3;
    private javax.swing.JButton Staff;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
