/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tiket.bioskop;

/**
 *
 * @author BEELZEBUB
 */
import java.awt.HeadlessException;
import java.awt.print.PrinterException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class Menu3 extends javax.swing.JFrame {

    /**
     * Creates new form Menu3
     */
    public Menu3() {
        initComponents();
        tampil_data();
    }
    public void bersih(){
        txtIDPesan.setText("");
        jamTayang.setText("");
        film.setText("");
        hari.setText("");
            jumlahTiket.setText("");
            kursi.setText("");
            harga.setText("");
            tanggal.setText("");
            studio.setText("");
    }

    
    public void cetak(){
        try{
            struk.setText("\t          CINEMA 256\n");
            struk.setText(struk.getText()+"\t      Jakarta, Indonesia\n");
            struk.setText(struk.getText()+"\t cinema256@gmail.com\n");
            struk.setText(struk.getText()+"==========================================\n");
            struk.setText(struk.getText()+"FIlm\t:   " + film.getText() + "\n");
            struk.setText(struk.getText()+"Jam Tayang\t:   " + jamTayang.getText() + "\n");
            struk.setText(struk.getText()+"Hari\t:   " + hari.getText() + "\n");
            struk.setText(struk.getText()+"Kursi\t:   " + kursi.getText() + "\n");
            struk.setText(struk.getText()+"Studio\t:   " + studio.getText() + "\n");
            struk.setText(struk.getText()+"Harga\t:   " + harga.getText() + "\n");
            struk.setText(struk.getText()+"==========================================\n");
            struk.setText(struk.getText()+"\t      Terimakasih\n");
            struk.setText(struk.getText()+"==========================================");
            //struk.print();
        }catch(Exception e){
            
        }
    }
    public void tampil_data() {
    try {
        java.sql.Connection conn = tiket.bioskop.Koneksi.getKoneksi();
        //String no = txtIDPesan.getText();
        //String sql = "SELECT jam_tayang, film, hari, jumlah_tiket, kursi, harga, tanggal, Studio_F FROM tbl_pesan WHERE id_pesan = ?";
        String sql = "SELECT * FROM tbl_pesan ORDER BY id_pesan DESC LIMIT 1";
        java.sql.PreparedStatement pst = conn.prepareStatement(sql);
        //pst.setString(1, no);
        ResultSet rs = pst.executeQuery();

        if (rs.next()) {
            txtIDPesan.setText(rs.getString(1));
            jamTayang.setText(rs.getString(2));
            film.setText(rs.getString(3));
            hari.setText(rs.getString(4));
            jumlahTiket.setText(rs.getString(5));
            kursi.setText(rs.getString(6));
            harga.setText(rs.getString(7));
            tanggal.setText(rs.getString(8));
            studio.setText(rs.getString(9));
            cetak();
        } else {
            // Tampilkan pesan jika data tidak ditemukan
            JOptionPane.showMessageDialog(null, "Data tidak ditemukan");
            bersih();

        }
    } catch (SQLException e) {
        e.printStackTrace();
    }
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtIDPesan = new javax.swing.JTextField();
        film = new javax.swing.JTextField();
        jamTayang = new javax.swing.JTextField();
        jumlahTiket = new javax.swing.JTextField();
        hari = new javax.swing.JTextField();
        kursi = new javax.swing.JTextField();
        harga = new javax.swing.JTextField();
        studio = new javax.swing.JTextField();
        tanggal = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        struk = new javax.swing.JTextArea();
        batalkan = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Cetak Tiket");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 30, -1, -1));

        jLabel3.setText("ID Pesan");

        jLabel4.setText("Film");

        jLabel5.setText("Jam Tayang");

        jLabel6.setText("Hari");

        jLabel7.setText("Jumlah Tiket");

        jLabel8.setText("Kursi");

        jLabel9.setText("Harga");

        jLabel10.setText("Tanggal");

        jLabel11.setText("Studio");

        txtIDPesan.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtIDPesan.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtIDPesan.setEnabled(false);

        film.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        film.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        film.setEnabled(false);

        jamTayang.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jamTayang.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jamTayang.setEnabled(false);

        jumlahTiket.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jumlahTiket.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jumlahTiket.setEnabled(false);

        hari.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        hari.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        hari.setEnabled(false);

        kursi.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        kursi.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        kursi.setEnabled(false);

        harga.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        harga.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        harga.setEnabled(false);

        studio.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        studio.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        studio.setEnabled(false);

        tanggal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tanggal.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        tanggal.setEnabled(false);

        struk.setColumns(20);
        struk.setRows(5);
        struk.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        struk.setEnabled(false);
        struk.setMargin(new java.awt.Insets(2, 6, 2, 6));
        jScrollPane1.setViewportView(struk);

        batalkan.setText("Batalkan");
        batalkan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batalkanActionPerformed(evt);
            }
        });

        jButton3.setText("Cetak");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(98, 98, 98)
                                        .addComponent(film, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jamTayang, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtIDPesan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(batalkan, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(22, 22, 22))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel10))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(hari, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                                    .addComponent(jumlahTiket)
                                    .addComponent(kursi)
                                    .addComponent(harga)
                                    .addComponent(studio)
                                    .addComponent(tanggal))))
                        .addGap(51, 51, 51))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtIDPesan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jamTayang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(1, 1, 1)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(film, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(5, 5, 5)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(hari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jumlahTiket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(kursi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(harga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(tanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(studio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(batalkan)
                    .addComponent(jButton3))
                .addGap(65, 65, 65))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 750, 420));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Aset/bgfix.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1070, 600));

        setBounds(0, 0, 1086, 639);
    }// </editor-fold>//GEN-END:initComponents

    private void batalkanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batalkanActionPerformed
        // TODO add your handling code here:
        try {
            String notelp = txtIDPesan.getText();

    if (notelp.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Nomor Id Pesan harus diisi terlebih dahulu");
    } else {
        java.sql.Connection conn = (java.sql.Connection) tiket.bioskop.Koneksi.getKoneksi();
        String sql = "DELETE FROM tbl_pesan WHERE id_pesan=?";
        java.sql.PreparedStatement pst = conn.prepareStatement(sql);
        pst.setString(1, notelp);
        int result = pst.executeUpdate();

        if (result > 0) {
            JOptionPane.showMessageDialog(null, "Pesanan berhasil dibatalkan");
            bersih();
            Menu2 su = new Menu2();
            su.show();
            dispose();
        } else {
            JOptionPane.showMessageDialog(null, "Proses pembatalan gagal");
        }
    }
} catch (HeadlessException | SQLException e) {
    JOptionPane.showMessageDialog(null, "Proses Pembatalan Gagal");
    System.out.println(e.getMessage());
}


    }//GEN-LAST:event_batalkanActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            String film_p = film.getText().toString();
            if (film_p.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Harap lengkapi semua field");
            } else {
                struk.print();
                Menu1 su = new Menu1();
                su.show();
                dispose();
            }
        } catch (PrinterException ex) {
            // Tangani exception jika terjadi kesalahan saat mencetak
            JOptionPane.showMessageDialog(null, "Terjadi kesalahan saat mencetak");
        }

    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton batalkan;
    private javax.swing.JTextField film;
    private javax.swing.JTextField harga;
    private javax.swing.JTextField hari;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jamTayang;
    private javax.swing.JTextField jumlahTiket;
    private javax.swing.JTextField kursi;
    private javax.swing.JTextArea struk;
    private javax.swing.JTextField studio;
    private javax.swing.JTextField tanggal;
    public javax.swing.JTextField txtIDPesan;
    // End of variables declaration//GEN-END:variables
}
